// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJYA1XvK3LbOLAwirqNDjMA2jmnPKQAaU',
    appId: '1:1045550723475:web:a1405380aec46d0fe6b866',
    messagingSenderId: '1045550723475',
    projectId: 'electivagrupo2-4be59',
    authDomain: 'electivagrupo2-4be59.firebaseapp.com',
    storageBucket: 'electivagrupo2-4be59.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBirlMzAgWCg7wkIZjR1r1jJJpzfwPysgE',
    appId: '1:1045550723475:android:441c0276f220dba3e6b866',
    messagingSenderId: '1045550723475',
    projectId: 'electivagrupo2-4be59',
    storageBucket: 'electivagrupo2-4be59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_dpAMOBfdbY_liXchRhsCkvT_DREGUdY',
    appId: '1:1045550723475:ios:923ecc576cc04a3de6b866',
    messagingSenderId: '1045550723475',
    projectId: 'electivagrupo2-4be59',
    storageBucket: 'electivagrupo2-4be59.firebasestorage.app',
    iosBundleId: 'com.example.parqueadero2025G2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_dpAMOBfdbY_liXchRhsCkvT_DREGUdY',
    appId: '1:1045550723475:ios:923ecc576cc04a3de6b866',
    messagingSenderId: '1045550723475',
    projectId: 'electivagrupo2-4be59',
    storageBucket: 'electivagrupo2-4be59.firebasestorage.app',
    iosBundleId: 'com.example.parqueadero2025G2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJYA1XvK3LbOLAwirqNDjMA2jmnPKQAaU',
    appId: '1:1045550723475:web:af972b6095117934e6b866',
    messagingSenderId: '1045550723475',
    projectId: 'electivagrupo2-4be59',
    authDomain: 'electivagrupo2-4be59.firebaseapp.com',
    storageBucket: 'electivagrupo2-4be59.firebasestorage.app',
  );
}
